# Generated by Django 4.2.16 on 2026-06-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
    ]
