# Generated by Django 4.2.16 on 2026-07-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_add_approved_by_column'),
        ('news', '0002_subscription'),
    ]

    operations = [
    ]
