# Generated by Django 4.2.16 on 2026-07-06 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_options_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
